# Generated by Django 4.0.5 on 2022-06-10 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.CharField(default='', max_length=256)),
                ('paid', models.CharField(default='', max_length=256)),
                ('cancel', models.CharField(default='', max_length=256)),
                ('left', models.CharField(default='', max_length=256)),
                ('arrived', models.CharField(default='', max_length=256)),
            ],
            options={
                'db_table': 'orderStatus',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('img', models.CharField(default='', max_length=256)),
                ('info', models.CharField(default='', max_length=256)),
                ('price', models.IntegerField(default='')),
                ('stock', models.IntegerField(default='')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default='')),
            ],
            options={
                'db_table': 'productOrder',
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=256)),
                ('order_time', models.DateTimeField(default='')),
                ('total_price', models.IntegerField(default='')),
                ('paid_price', models.IntegerField(default='')),
                ('discount_rate', models.FloatField(default='')),
                ('expiration', models.BooleanField(default='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.orderstatus')),
            ],
            options={
                'db_table': 'userOrder',
            },
        ),
    ]
