# Generated by Django 4.0.5 on 2022-06-10 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderstatus',
            old_name='arrived',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='cancel',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='left',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='paid',
        ),
    ]
